import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopHeader from "@/components/topHeader";
import Footer from "@/components/footer";

import Header from "@/components/header";
import { CartProvider } from "./context/cartContext";
const geistSans = localFont({
  src: "/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const integralCFbold = localFont({
  src: '../../public/font/Fontspring-DEMO-integralcf-bold.otf',
  variable: "--font-integralCfbold",
  weight: "700",
});
const satoshibold = localFont({
  src: "../../public/font/Satoshi-Bold.woff2",
  variable: "--font-satoshibold",
  weight: "700",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${integralCFbold.variable} ${satoshibold.variable} ${integralCFbold.variable} ${satoshibold.variable} antialiased`}
      >
        <TopHeader/>
        <Header />
  <CartProvider>

<main className="h-[100vh]">

        {children}
</main>
  </CartProvider>
       
        
<div className="relative bottom-0">

        <Footer />
</div>
        
       
      </body>
    </html>
  );
}
